site_name: EmailVerify for Discord
repo_url: https://github.com/lkaesberg/EmailVerify
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot-border.png
  favicon: https://raw.githubusercontent.com/lkaesberg/EmailBot/main/images/emailbot.png
  palette:
    scheme: default
    primary: black
    accent: yellow
  features:
    - navigation.tabs
nav:
  - 'index.md'
  - 'commands.md'
  - 'statistics.md'
  - 'contributing.md'
  - 'legal.md'
  - Buy Me a Coffee❤️: https://buymeacoffee.com/sral12486
